from django.urls import path, include
from app.views import (
    Index,
    UserProfile,
    UserProfileUpdate,
    AccountList,
    AccountTransfer,
    BankList,
    BankCreate,
    BankDetail,
    BankUpdate,
    BankDelete,
    CardList,
    CardCreate,
    CardDetail,
    CardUpdate,
    CardDelete,
    SendSearchUser,
    SendMoney,
    SendSuccess,
    RequestSearchUser,
    RequestMoney,
    RequestSuccess,
    ActivityList,
    IncompleteTranList,
    IncompletePayment,
    IncompletePaymentConfirm,
    PaymentComplete,
    IncompleteRequest,
    IncompleteRequestDelete,
    StaffTransactionList,
    StaffTranDetail,
    StaffTranDelete,
    StaffUserList,
    StaffUserInfo,
    StaffUserTran,
    StaffUserTranDetail,
    StaffUserTranDelete,
    StaffUserPayment,
    StaffUserBankDetail,
    StaffUserCardDetail,
    #payment_details,
    paypal_payment_process,
    paypal_payment_done,
    paypal_payment_canceled,
    paytm_payment_process,
    paytm_callback,

    IndexView,
    CreateAccountView,
    LoginView,
    OTPView,
    RegisterView,
    RecordPlayView,
    SetupVoiceView,
    TapListenView,
    VerifyProceedView,
    ProvidersView,
    MobileRechargeView,
    BillFoundView,
    DTHRechargeView,
    MobilePostpaidView,
    LandlineView,
    ElectricityView,
    WaterView,
    PipedgasView,
    FASTagView,
    LoanRepaymentView,
    BroadbandView,
    LpgGasView,
    InsurancePaymentView,
    SubscriptionView,
    SendMoneyView,
    SendVoiceMoneyView,
    RequestMoneyView, 
    RequestVoiceMoneyView,
    VoiceAuthenticationView,
    ScanPayView,
    DashboardView,
    SettingView,
    PersonalInformationView,
    NotificationEmailsView,
    PrivacySecurityView,
    AboutView,
    HelpFeedbackView,
    EditMobileNumberView,
    EditLanguageView,
    DataPersonalizationView,
    BlockedPeopleView,
    HowPeopleView,
    TermsServicesView,
    PrivacyPolicyView,
    SoftwareLicenseView,
    UserProfileView,
    DrawNumberGameView,
)

urlpatterns = [
    #path('index/', Index.as_view(), name='index'), #checked
    path('profile/', UserProfile.as_view(), name='profile'),    #checked
    path('profile/edit/', UserProfileUpdate.as_view(), name='profile_update'), #checked
    path('wallet/', AccountList.as_view(), name='account'), #checked
    path('transfer/<int:pk>/', AccountTransfer.as_view(), name='account_transfer'),
    path('bank/', BankList.as_view(), name='bank'),
    path('bank/add/', BankCreate.as_view(), name='bank_create'),
    path('bank/<int:pk>/detail/', BankDetail.as_view(), name='bank_detail'),
    path('bank/<int:pk>/update/', BankUpdate.as_view(), name='bank_update'),
    path('bank/<int:pk>/delete/', BankDelete.as_view(), name='bank_delete'),
    path('card/', CardList.as_view(), name='card'),
    path('card/add/', CardCreate.as_view(), name='card_create'),
    path('card/<int:pk>/detail/', CardDetail.as_view(), name='card_detail'),
    path('card/<int:pk>/update/', CardUpdate.as_view(), name='card_update'),
    path('card/<int:pk>/delete/', CardDelete.as_view(), name='card_delete'),
    path('activity/', ActivityList.as_view(), name='activity'),
    path('send/', SendSearchUser.as_view(), name='send'),
    path('send/<int:pk>/', SendMoney.as_view(), name='send_money'),
    path('send/success/', SendSuccess.as_view(), name='send_success'),
    path('request/', RequestSearchUser.as_view(), name='request'),
    path('request/<int:pk>/', RequestMoney.as_view(), name='request_money'),
    path('request/success/', RequestSuccess.as_view(), name='request_success'),
    path('incomplete/', IncompleteTranList.as_view(), name='incomplete'),
    path('incomplete/payment/<int:pk>/detail/', IncompletePayment.as_view(), name='incomplete_payment'),
    path('incomplete/payment/<int:pk>/confirm/', IncompletePaymentConfirm.as_view(), name='incomplete_payment_confirm'),
    path('incomplete/payment/complete/', PaymentComplete.as_view(), name='payment_complete'),
    path('incomplete/request/<int:pk>/detail/', IncompleteRequest.as_view(), name='incomplete_request'),
    path('incomplete/request/<int:pk>/delete/', IncompleteRequestDelete.as_view(), name='incomplete_request_delete'),
    path('staff/transaction/', StaffTransactionList.as_view(), name='staff_transaction'),
    path('staff/transaction/<int:pk>/detail/', StaffTranDetail.as_view(), name='staff_tran_detail'),
    path('staff/transaction/<int:pk>/delete/', StaffTranDelete.as_view(), name='staff_tran_delete'),
    path('staff/user/', StaffUserList.as_view(), name='staff_user'),
    path('staff/user/<int:pk>/info/', StaffUserInfo.as_view(), name='staff_user_info'),
    path('staff/user/<int:pk>/payment/', StaffUserPayment.as_view(), name='staff_user_pay'),
    path('staff/user/<int:pk>/bank/<int:bpk>', StaffUserBankDetail.as_view(), name='staff_user_bank'),
    path('staff/user/<int:pk>/card/<int:cpk>/', StaffUserCardDetail.as_view(), name='staff_user_card'),
    path('staff/user/<int:pk>/transactions/', StaffUserTran.as_view(), name='staff_user_tran'),
    path('staff/user/<int:pk>/transactions/<int:tpk>/detail', StaffUserTranDetail.as_view(), name='staff_user_tran_detail'),
    path('staff/user/<int:pk>/transactions/<int:tpk>/delete', StaffUserTranDelete.as_view(), name='staff_user_tran_delete'),
    #path("/start/", "start", name="dcavenue-start"),
    #path("/callback/", "callback", name="dcavenue-callback"),
    #path('payments/', include('payments.urls')),
    #path('payment_start/<int:payment_id>/', payment_details, name='payment_detail'),
    path('payment/process/', paypal_payment_process, name='paypal_process'),
    path('payment/done/', paypal_payment_done, name='paypal_done'),
    path('payment/canceled/', paypal_payment_canceled, name='paypal_canceled'),

    path('payment/paytm/process/', paytm_payment_process, name='paytm_payment_process'),
    path('payment/paytm/callback/', paytm_callback, name='paytm_callback'),
    
    path('', IndexView.as_view(), name='index'),
    path('create_account/', CreateAccountView.as_view(), name='create_account'),
    path('paybill_login/', LoginView.as_view(), name='paybill_login'),
    path('otp/', OTPView.as_view(), name='otp'),
    path('register/', RegisterView.as_view(), name='register'),
    path('record_play/', RecordPlayView.as_view(), name='record_play'),
    path('setup_voice/', SetupVoiceView.as_view(), name='setup_voice'),
    path('tap_listen/', TapListenView.as_view(), name='tap_listen'),
    path('verify_proceed/', VerifyProceedView.as_view(), name='verify_proceed'),
    path('providers/', ProvidersView.as_view(), name='providers'),
    path('providers/mobile_recharge/', MobileRechargeView.as_view(), name='mobile_recharge'),
    path('providers/bill_found/', BillFoundView.as_view(), name='bill_found'),
    path('providers/dth_recharge/', DTHRechargeView.as_view(), name='dth_recharge'),
    path('providers/mobile_postpaid/', MobilePostpaidView.as_view(), name='mobile_postpaid'),  
    path('providers/landline/', LandlineView.as_view(), name='landline'),  
    path('providers/electricity/', ElectricityView.as_view(), name='electricity'),  
    path('providers/water/', WaterView.as_view(), name='water'),  
    path('providers/piped_gas/', PipedgasView.as_view(), name='piped_gas'),  
    path('providers/FASTag/', FASTagView.as_view(), name='fastag'),  
    path('providers/loan_repayment/', LoanRepaymentView.as_view(), name='loan_repayment'),  
    path('providers/broadband/', BroadbandView.as_view(), name='broadband'),  
    path('providers/lpg_gas/', LpgGasView.as_view(), name='lpg_gas'),
    path('providers/insurance_payment/', InsurancePaymentView.as_view(), name='insurance_payment'),
    path('providers/subscription/', SubscriptionView.as_view(), name='subscription'),
    path('send_money/', SendMoneyView.as_view(), name='paybills_send_money'),
    path('send_voice_money/', SendVoiceMoneyView.as_view(), name='send_voice_money'),
    path('request_money/', RequestMoneyView.as_view(), name='request_money'),
    path('request_voice_money/', RequestVoiceMoneyView.as_view(), name='request_voice_money'),
    path('voice_authentication/', VoiceAuthenticationView.as_view(), name='voice_authentication'),
    path('scan_pay/', ScanPayView.as_view(), name='scan_pay'), 
    path('dashboard/', DashboardView.as_view(), name='dashboard'), 
    path('setting/', SettingView.as_view(), name='setting'), 
    path('personal_info/', PersonalInformationView.as_view(), name='personal_info'), 
    path('notification_email/', NotificationEmailsView.as_view(), name='notification_email'), 
    path('privacy_security/', PrivacySecurityView.as_view(), name='privacy_security'), 
    path('about/', AboutView.as_view(), name='about'), 
    path('help_feedback/', HelpFeedbackView.as_view(), name='help_feedback'), 
    path('personal_info/edit_mobile_number/', EditMobileNumberView.as_view(), name='edit_mobile_number'), 
    path('personal_info/edit_language/', EditLanguageView.as_view(), name='edit_language'),      
    path('privacy_security/data_personalization/', DataPersonalizationView.as_view(), name='data_personalization'),      
    path('privacy_security/blocked_people/', BlockedPeopleView.as_view(), name='blocked_people'),      
    path('privacy_security/how_people_find_you/', HowPeopleView.as_view(), name='how_people_find_you'),      
    path('about/terms_services/', TermsServicesView.as_view(), name='terms_services'),      
    path('about/privacy_policy/', PrivacyPolicyView.as_view(), name='privacy_policy'),      
    path('about/software_license/', SoftwareLicenseView.as_view(), name='software_license'), 
    path('dashboard/user_profile/', UserProfileView.as_view(), name='user_profile'),      
    path('draw_number_game/', DrawNumberGameView.as_view(), name='draw_number_game'),      
]  

