"""
Django settings for paybills project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from django.urls import reverse_lazy
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import environ
env = environ.Env()
environ.Env.read_env()  # reading .env file

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# Modify it for production
DEBUG = True
#DEBUG = False

ALLOWED_HOSTS = [
    'localhost',
    '.localhost',
    '127.0.0.1',
    '45e5b56653bc.ngrok.io',
    'paybills.today',
    '.paybills.today', #To allow subdomain
    'https://paybills.today',
    ]

# Modify it for production
DEFAULT_SITE_DOMAIN = "localhost:8000"
#DEFAULT_SITE_DOMAIN = "paybills.today"

# Modify it for production
HTTP_PROTOCOL = "http"
#HTTP_PROTOCOL = "https"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cities',
    'timezone_field',
    'formtools',
    'app',
    #'payments', #For django-payments
    #'paypal.standard.ipn', #paypal integration
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'paybills.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'app/templates/app')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'paybills.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""

#MySQL DB configurations

# DATABASES = {
#     'default': {
#         'ENGINE': "django.db.backends.mysql",
#         'NAME': "paybills_db", #database name of mysql instance
#         'USER' : "admin", 
#         'PASSWORD' : "admin123",
#         'HOST' : "localhost", #public IP of mysql instance
#         'PORT' : "3306",
#     }
# }

DATABASES = {
    'default': {
        #'ENGINE': "django.db.backends.mysql",
        'ENGINE' : "django.contrib.gis.db.backends.mysql",
        'NAME': env('DB_SCHEMA_NAME'), #database name of mysql instance
        'USER' : env('DB_USER'), 
        'PASSWORD' : env('DB_PASSWORD'),
        'HOST' : env('DB_HOST'), #public IP of mysql instance
        'PORT' : env('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/' #URL to access static files
STATIC_ROOT = os.path.join(BASE_DIR, "static") #Location to store all the static files from multiple apps
MEDIA_URL = 'media/'
#Additional location to traverse for static files
#STATICFILES_DIRS = [
    #BASE_DIR / "app/static"
#]


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Added

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

"""
#dcavenue configurations
DCAVENUE = {
    "MERCHANT\_ID": "<your merchant key>",
    "WORKING\_KEY": "<32 bit working key>", # len must be 32
}
"""
"""
#django-payments configurations
PAYMENT_HOST = 'localhost:8000'
PAYMENT_USES_SSL = False
PAYMENT_MODEL = 'app.Payment'
PAYMENT_VARIANTS = {
    'default': ('payments.dummy.DummyProvider', {})} #For thrid party gateway APIs
"""
"""
# use sandbox
PAYMENT_VARIANTS = {
    'paypal': ('payments.paypal.PaypalProvider', {
        'client_id': 'user@example.com',
        'secret': 'iseedeadpeople',
        'endpoint': 'https://api.sandbox.paypal.com',
        #'endpoint': 'https://api.paypal.com',
        'capture': False})}
"""

#django-paypal configurations
PAYPAL_TEST = env('PAYPAL_TEST')
PAYPAL_RECEIVER_EMAIL = env('PAYPAL_RECEIVER_EMAIL')

#Paytm configurations
PAYTM_MERCHANT_ID = 'yourmerchantid'
PAYTM_SECRET_KEY = '1234123412341234'
PAYTM_WEBSITE = 'WEBSTAGING'
PAYTM_CHANNEL_ID = 'WEB'
PAYTM_INDUSTRY_TYPE_ID = 'Retail'

AUTH_USER_MODEL = "app.UserModel"

#Added to store audio files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_root')

PRODUCT_IMAGE_LOCATION = 'products/'
MERCHANT_LOGO = 'merchants/'

#SendGrid API key
SENDGRID_API_KEY="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" 

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'apikey' # this is exactly the value 'apikey'
EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_SENDER = "evasmith363@gmail.com"

#End the user session on browser close
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SIGNUP_URL = "https://paybills.today/"

#Razorpay credentials
RAZORPAY_KEY_ID = "rzp_test_eq6mWqX0HTle7a"
RAZORPAY_KEY_SECRET = "CNXi3dGMeHKxMC7aexuuy70d"

CCAVENUE_MERCHANT_ID = 162094

SESSION_COOKIE_SECURE  = True
CSRF_COOKIE_SECURE = True
#Causing err-to-many-redirects
#SECURE_SSL_REDIRECT = True
